import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/global.css";
import ClientSessionProvider from "@components/provider/ClientProvider";
import Header from "@components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MatDot",
  description: "Generated by MatDot",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          <Header />
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  );
}
